language: node_js
node_js:
- 8
deploy:
  provider: heroku
  api_key:
    secure: BmdbUGxNIEgEjXF8xYP6rEcxp5XlIgZ62BotJNTBEp7oouNXLtkO7RpsV/EP7Toixl9BQ7z4Oiw6uAo7lrcaWlYKvmOtmnqZuaPcG0DuCXFqCqOdgCg3hPIcH45TbAc8BhaD5gIWZQf5JYdIeA0NhVhW29vxPcnD4vyFzUGZKORLxHDJucTUOFsYSTEMLd/Pp9D0DcOfJ7wtI+ofcDS1eUQCkqjAJCEahn4li1+RhpqhM5yzRgDXONU0qJFrRdq5NmCY2Dcwyp/SuTg/3nlFFIypHkaYZLOM3dYVZDSqSc193w3ioS3pMmELKU5DApNQW1gxXWt11Q+hUasYqod6U2QfrUFmj0JYSlIu84tuws0gSr05YTi8pqQxnsWTEJ2Bzc/+HP7kJKxzqxbc2fnrum4iVMymUUVvoTVEeIZdnglzqEprtTCV1aajC8BGydnAHP/Ge3D0NKOZicDaGQu4DzRy06OODXroEXOmoI3jbTMFGiqPJKOZgMrj4YC23WfvwWrmvloZnIT4LqHEqixgqXAzJepZWuMpEbGT6XirQwqZWLOLKWkFImuMVJ4kgqPqRSLUkcyG/6NtW+vLeP0ntFpoZmA9XL2aHoxYumwt7QdKKXGlVoZety0YRTOQoKjurxQqcotjle8+10+BhX9Eh3s8YK4OsmpWkNRPEsFwxio=
  app: epichatapi
